### ISSUE TITLE
Presensi Keluar

### ISSUE THREAD

**Issue by jaelani757** [josephines1/o-present#4]

**Comment by jaelani757** [comment]
hallo kak, izin untuk presensi keluar  bisa d akses kalau udah 8 jam kerja ya?

**Comment by josephines1** [comment]
Halo kak jaelani757, untuk presensi keluar bisa diakses setelah jam pulang yang diatur di lokasi presensi seperti ini kak.

![image](https://github.com/user-attachments/assets/d786b5d6-0ab9-4927-8cd3-275aade8eb0b)

**Comment by jaelani757** [comment]
saya udah nyoba presensi masuk dan langsung bisa presensi keluar kak

**Comment by josephines1** [comment]
Bisa jadi ini karena presensi masuknya dilakukan setelah jam presensi keluar yang sudah diatur di lokasi presensinya kak.

**Comment by mrandrian** [comment]
<img width="1280" alt="Screenshot 2024-08-28 at 10 12 02" src="https://github.com/user-attachments/assets/12e835ab-16fc-42c2-b21c-4a11f6e38cf2">
Saya mencobanya pada hosting dengan web server nginx. Terdapat error setelah mencoba presensi masuk

**Comment by josephines1** [comment]
Halo kak @mrandrian, mungkin bisa ubah environment di file `.env` terlebih dahulu dari production menjadi **development** agar kita bisa cari tahu masalahnya seperti apa.

**Comment by mrandrian** [comment]
Halo kak @josephines1 sudah saya rubah file `.env` ke **development**, namun tampilan tetap sama, tidak menampilkan log apapun

**Comment by josephines1** [comment]
apakah sudah un-comment baris environment nya kak?

dari
 `# CI_ENVIRONMENT = production` 

menjadi 
`CI_ENVIRONMENT = development`

**Comment by josephines1** [comment]
Apakah pesan error lengkap nya seperti ini kak?

![image](https://github.com/user-attachments/assets/d493c95c-e6cd-4a0d-928b-ffc83f93d5a2)

Jika iya, error tersebut muncul karena folder `public\assets\img\foto_presensi\masuk` tidak terdeteksi. Mohon maaf saya lupa untuk mengupload nya ke github. Bisa ditambahkan saja kak folder baru `public\assets\img\foto_presensi\masuk` dan `public\assets\img\foto_presensi\keluar`. 

Terimakasih untuk report nya ya kak @mrandrian.

**Comment by mrandrian** [comment]
Oh oya betul kak @josephines1 sekrang sudah solved

**Comment by mrandrian** [comment]
Sedikit info untuk pengguna ios terdapat bug, yang dimana terdapat pesan error `“Origin Does Not Have Permission to use Geolocation Service”` saat ingin melakukan absen, solusinya tambahkan header berikut pada konfigurasi web server `add_header Content-Security-Policy "upgrade-insecure-requests";` 

note: web server yang saya gunakan adalah NGINX

**Comment by josephines1** [comment]
Terima kasih untuk masukkan nya, izin saya cantumkan solusi ini di readme ya kak @mrandrian 🙏🏻

**Comment by mrandrian** [comment]
Silahkan kak @josephines1 dengan senang hati
