### ISSUE TITLE
Cara buat password untuk login pegawai

### ISSUE THREAD

**Issue by mrandrian** [josephines1/o-present#5]
Pada saat pembuatan pegawai baru tidak ada menu set password

**Comment by josephines1** [comment]
Halo kak @mrandrian, untuk saat ini tidak ada menu set password untuk pembuatan pegawai baru. Pegawai baru dapat mengakses akun nya dengan password default **123456**, lalu melakukan reset password nya secara mandiri di halaman Profile setelah melakukan aktivasi akun.
