### ISSUE TITLE
tidak menemukan folder vendor

### ISSUE THREAD

**Issue by kevinsurya123** [josephines1/o-present#7]
saya tidak dapat menemukan : vendor\myth\auth\src\Controllers\AuthController.php

**Comment by josephines1** [comment]
Halo, apakah sudah menjalankan perintah `composer install` kak?

**Comment by kevinsurya123** [comment]
> Halo, apakah sudah menjalankan perintah `composer install` kak?

eror mucul seperti ini

ACER@DESKTOP-SK5ARGQ MINGW64 /c/xampp/htdocs/o-present (main)
$ composer install
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - phpoffice/phpspreadsheet is locked to version 1.29.0 and an update of this package was not requested.
    - phpoffice/phpspreadsheet 1.29.0 requires ext-gd * -> it is missing from your system. Install or enable PHP's gd extension.

To enable extensions, verify that they are enabled in your .ini files:
    - C:\xampp\php\php.ini
You can also run `php --ini` in a terminal to see which files are used by PHP in CLI mode.
Alternatively, you can run Composer with `--ignore-platform-req=ext-gd` to temporarily ignore these required extensions.

**Comment by josephines1** [comment]
Untuk mengatasi error tersebut bisa coba cara ini kak:

1. Buka file `php.ini` (biasanya terletak di direktori `C:\xampp\php\php.ini`)
2. Ctrl + F di editor teks dan cari `;extension=gd`.
3. Hilangkan tanda titik koma (;) di depan baris `extension=gd`. Jadi, ubah dari:
`;extension=gd`
menjadi 
`extension=gd`

Simpan file php.ini lalu jalankan ulang perintah `composer install`

semoga membantu ya kak.

**Comment by kevinsurya123** [comment]
terimakasih sangat membantu, namun bagaimana untuk eror yang ini
![eror login](https://github.com/user-attachments/assets/37a42660-2df5-41b3-bb20-a3bc56264a41)

**Comment by josephines1** [comment]
apakah sudah memodifikasi function before menjadi seperti berikut ini kak?

```
public function before(RequestInterface $request, $arguments = null)
 {
     // If no user is logged in then send them to the login form.
     if (! $this->authenticate->check()) {
         session()->set('redirect_url', current_url());

         return redirect($this->reservedRoutes['login']);
     }

     if (empty($arguments)) {
         return;
     }

     // Check each requested permission
     foreach ($arguments as $group) {
         if ($this->authorize->inGroup($group, $this->authenticate->id())) {
             return;
         }
     }

     // Check if the user has the 'head' role
     if ($this->authorize->inGroup('head', $this->authenticate->id())) {
         // Check each requested permission for 'head'
         if (!empty($arguments)) {
             foreach ($arguments as $group) {
                 if ($this->authorize->inGroup($group, $this->authenticate->id())) {
                     return;
                 }
             }

             // If 'head' does not have the required permission, redirect to '/admin'
             return redirect()->to('/admin')->with('error', lang('Auth.notEnoughPrivilege'));
         }
     }

     if ($this->authenticate->silent()) {
         $redirectURL = session('redirect_url') ?? route_to($this->landingRoute);
         unset($_SESSION['redirect_url']);

         return redirect()->to($redirectURL)->with('error', lang('Auth.notEnoughPrivilege'));
     }

     // throw new PermissionException(lang('Auth.notEnoughPrivilege'));
     return redirect()->to('/');
 }
```

**Comment by kevinsurya123** [comment]
Hanya muncul sampai bagian login, setelah memasukan username & password, web nya loading lama sampai muncul seperti ini

![Uploading IMG_20241016_152540.jpg…]()

**Comment by josephines1** [comment]
Izin memastikan sebelumnya kak, apakah langkah-langkah konfigurasi di https://github.com/josephines1/o-present?tab=readme-ov-file#getting-started sudah dijalankan semua nya? 

Jika sudah, dan web nya masih loading terlalu lama, mungkin bisa dicoba konfigurasi di `php.ini`, cari `session.save_path`, lalu hilangkan tanda titik koma nya jika ada.

**Comment by kevinsurya123** [comment]
Solved, ty
