### ISSUE TITLE
Tidak bisa login

### ISSUE THREAD

**Issue by kevinsurya123** [josephines1/o-present#8]
Hi @josephines1 sorry ganggu lagi, tadi aku nyoba buat login di laptop, tapi justru habis klik login jadi balik ke home, check this

https://drive.google.com/file/d/1G7Q6-zN66xpRccOgoWHm9jS_MuOQLrMe/view?usp=drivesdk

Terimakasih 🙏👻

**Comment by josephines1** [comment]
Halo kak @kevinsurya123, untuk button "masuk" yang ada pada video itu untuk melakukan presensi masuk, dan kalau setelah button itu diklik tidak ada aksi apapun dan langsung dikembalikan ke halaman Home, itu biasanya karena masalah koneksi kak. Semoga bisa membantu ya kak jawaban saya.

**Comment by kevinsurya123** [comment]
Terimakasih, terakhir janji bgt 🥹, unsble to send email (forgot password) seperti tampilan dibawah ini
![IMG_20241018_115109](https://github.com/user-attachments/assets/794eb5f8-dda0-4ad5-b6c0-a485b134ba12)
Kenapa ya kak kira kira

**Comment by josephines1** [comment]
Untuk error yang unable to send email itu karena password smtp yang dimasukkan tidak valid kak. Password smtp yang dimaksud bukan kode cadangan, melainkan **sandi aplikasi**, untuk generate sandi aplikasi atau app password ini lebih jelasnya bisa cek video ini kak https://www.youtube.com/watch?v=MkLX85XU5rU.

**Comment by kevinsurya123** [comment]
> Untuk error yang unable to send email itu karena password smtp yang dimasukkan tidak valid kak. Password smtp yang dimaksud bukan kode cadangan, melainkan **sandi aplikasi**, untuk generate sandi aplikasi atau app password ini lebih jelasnya bisa cek video ini kak https://www.youtube.com/watch?v=MkLX85XU5rU.

Terimakasih, solved...
